# Order of operations
stages:
  - test

test:
  stage: test
  image: node:8.12.0-alpine
  cache:
    paths:
      - node_modules
  services:
    - postgres:10.5
  variables:
    CI: 'true'
    TYPEORM_CONNECTION: 'postgres'
    TYPEORM_HOST: 'postgres'
    TYPEORM_PORT: '5432'
    TYPEORM_USERNAME: 'postgres'
    TYPEORM_PASSWORD: 'postgres'
    TYPEORM_DATABASE: 'postgres'
    TYPEORM_SYNCHRONIZE: 'true'
  script:
    - yarn
    - yarn build:env
    - cat .env
    - yarn db:init
    - yarn test
    - yarn test:e2e
