# Order of operations
stages:
  - test

test:
  stage: test
  image: node:8.12.0-alpine
  cache:
    paths:
      - node_modules
  services:
    - postgres:10.5
  variables:
    TYPEORM_HOST: postgres
  script:
    - yarn
    - yarn db:init
    - yarn test
    - yarn test:e2e
